# Copyright 2022-2024 TII (SSRC) and the Ghaf contributors
# SPDX-License-Identifier: Apache-2.0

version = 1
SPDX-PackageName = "ghaf-caml-crush"
SPDX-PackageSupplier = "Technology Innovation Institute <https://tii.ae>"
SPDX-PackageDownloadLocation = "https://github.com/tiiuae/ghaf-caml-crush"

[[annotations]]
SPDX-License-Identifier = "Apache-2.0"
SPDX-FileCopyrightText = "2022-2024 TII (SSRC) and the Ghaf contributors"
precedence = "closest"
path = [
  ".github/*",
  " *.lock",
  "*.json",
  "docs/*.svg",
  "*.conf"
]
