name: fmt-check

on:
  pull_request:
    branches:
      - main
jobs:
  checks:
    name: Run .nix formatting checks before allowing merging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
      - name: Check .nix formatting
        run: nix fmt -- --fail-on-change
